baseURL = 'https://OctopusZh.github.io/'
languageCode = 'en-us'
title = "OctopusZh's Blog"
theme = ["lightbi-hugo"]
defaultContentLanguage = "en"
languageName = "English"
hasCJKLanguage = true
paginate = 10
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
copyright = "OctopusZh"
publishDir = '../docs'

[Params]
mainSections = ["post","posts"]
dateFormat = "02 January 2006"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
lunrSearch = true
gcse = false
lastmod = false
rss = false
pagination = "10"
hideAuthor = false
description="OctopusZH writing memories here"
previewCardImagePlacement = "bottom"

[Params.Author]
  name = "OctopusZH"
  website = "https://OctopusZh.github.io"
  authorInfo = "Reading, traveling, coding."
  authorPostImage = "/img/author.png"

[Author]
  name = "OctopusZH"
  website = "https://OctopusZh.github.io"
  email = "dongliang_cq@qq.com"
  #facebook = "username"
  #instagram = "username"
  #youtube = "user/username"
  #twitter = "username"
  #linkedin = "username"
  github = "OctopusZH"
  #threads = "username"
  #gitlab = "username"
  #reddit = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #spotify = "username"
  #paypal = "username"
  #telegram = "username"
  #mastodon = "url"
  #slack = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #500px = "username"
  #kaggle = "username"
  #weibo = "username"
  #xing = "username"
  #bitbucket = "username"
  #soundcloud = "username"
  #codepen = "username"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
